baseURL = "https://ki8ji.org/"
locale = 'en-us'
title = "KI8JI"
theme = "stack"
mainSections = ["posts"]


[params]
	math = true
				
[markup.goldmark.extensions.passthrough]
	enable = true
	
[markup.goldmark.extensions.passthrough.delimiters]
	block = [['\[', '\]'], ['$$', '$$']]
	inline = [['\(', '\)']]