[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Essays"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Antennas"
  url = "/tags/antennas/"
  weight = 30

[[main]]
  name = "Boatanchors"
  url = "/tags/boatanchors/"
  weight = 40

[[main]]
  name = "Modeling"
  url = "/tags/modeling/"
  weight = 50

[[main]]
  name = "Homebrew"
  url = "/tags/homebrew/"
  weight = 60

[[main]]
  name = "Instruments"
  url = "/tags/instruments/"
  weight = 70

[[main]]
  name = "Theory"
  url = "/tags/theory/"
  weight = 80

[[main]]
  name = "Gear"
  url = "/tags/gear/"
  weight = 90

[[main]]
  name = "Station"
  url = "/tags/station/"
  weight = 100
